output "resource_group" {
  value       = azurerm_resource_group.main.name
  description = "The resource group."
}

output "pgsql_server_url" {
  value       = module.pgsql_database.database_url
  description = "Postgresql Database server url"
}

output "pgsql_user_name" {
  value       = module.pgsql_database.database_username
  description = "The PostgreSQL user name"
}

output "mysql_server_url" {
  value       = module.mysql_database.database_url
  description = "MySql Database server url"
}

output "mysql_user_name" {
  value       = module.mysql_database.database_username
  description = "The MySql user name"
}

output "container_registry_name" {
  value       = module.application.container_registry_name
  description = "The Docker Container Registry name generated by the Azure Cloud Adoption Framework."
}
